export const MONIKERS_WORD_BANK = [
    'Doge',
    'A Russian Nesting Doll',
    'Rick Santorum',
    'Blacula',
    'Georgia O\'keeffe',
    'Ebola',
    'A Furry',
    'Gallagher',
    'Kobayashi',
    'Flying Spaghetti Monster',
    'Sylvia Plath',
    'The Unabomber (ted Kaczynski)',
    'Pablo Escobar',
    'El Chupacabra',
    'Bill Cosby',
    'Bob Fosse',
    'Heisenberg',
    'Rosie The Riveter',
    'A Narwhal',
    'Hitler\'s Brain',
    '100 Duck-sized Horses',
    'Achilles',
    'Che Guevara',
    'A Velociraptor',
    'Homo Erectus',
    'William Howard Taft',
    'L. Ron Hubbard',
    'Shirtless Vladimir Putin',
    'Christopher Walken',
    'Baby Jessica',
    'Jackson Pollock',
    'Caligula',
    'Julian Assange',
    'The Pied Piper',
    'Atlas',
    'Pavlov\'s Dog',
    'Oscar Pistorius',
    'Leeroy Jenkins',
    'Lou Gehrig',
    'Elian Gonzalez',
    'A Raver',
    'Ai Roker',
    'Charlton Heston',
    'Jacques Cousteau',
    'Mr. Trololo',
    'Evander Holyfield\'s Ear',
    'Hodor',
    'A Communist',
    'Khalid Sheikh Mohammed',
    'The 99%',
    'Richard Pryor',
    'Rosa Parks',
    'An Illusionist',
    'A Castrato',
    'A Baby Sloth',
    'Kurt Cobain',
    'Tonya Harding',
    'A Mole',
    'Prince',
    'A Beard',
    'God',
    'The Lady Who Spilled Coffee On Herself At Mcdonald\'s',
    'Anne Frank',
    'Deep Blue',
    'Pee-wee Herman',
    'An Oompa Loompa',
    'Rapunzel',
    'Pac-man',
    'Godzilla',
    'Man Hands',
    'John Wilkes Booth',
    'The Very Hungry Caterpillar',
    'A Human Centipede',
    'Amelia Earhart',
    'Vincent Van Gogh',
    'Abraham Lincoln',
    'Mr. Owl',
    'A Grammar Nazi',
    'Yoshi',
    'Hannibal Lector',
    'A Centaur',
    'Dr. Henry Heimlich',
    'The Shoe Bomber (richard Reid)',
    'Slimer',
    'Magic Mike',
    'Drunk Jeff Goldblum',
    'Princess Di',
    'The Raven',
    'The Loch Ness Monster',
    'Teddy Ruxpin',
    'Rosemary\'s Baby',
    'Your Mom',
    'The Swedish Chef',
    'The Eye Of Sauron',
    'Bubble Boy',
    'Bloody Mary',
    'Colonel Sanders',
    'O.j. Simpson',
    'The Hamburglar',
    'A Leper',
    'Khan!',
    'The Kaiser',
    'A California Raisin',
    'A Hungry Hungry Hippo',
    'Aunt Jemima',
    'Jesus H. Christ',
    'The Kraken',
    'A Tsa Agent',
    'A Cylon',
    'Splinter',
    'Babar',
    'The Underwear Bomber',
    'Chun-li',
    'The T-1000',
    'Cthulhu',
    'A Muggle',
    'A Fainting Goat',
    'Count Chocula',
    'Burning Man',
    'A Furby',
    'Paul Reubens',
    'A Sherpa',
    'Ei Niño',
    'Ceiling Cat',
    'The Yellow Power Ranger',
    'The One-armed Drummer From Def Leppard',
    'Uncle Tom',
    'George Washington',
    'The Lord Of The Dance',
    'Goatse',
    'P.f. Chang',
    'Oedipus',
    'A Bleeder',
    'A Roomba',
    'Teen Wolf',
    'Falkor',
    'The Trojan Horse',
    'A Bro',
    'Paula Deen',
    'Octomom (nadya Suleman)',
    'A Hoarder',
    'A Neanderthal',
    'Damien Hirst',
    'Deep Throat',
    'William Shatner',
    'The Tiger Mom',
    'Blackfish',
    'The Gerber Baby',
    'Poppin\' Fresh, The Pillsbury Doughboy',
    'Krang',
    'Humpty Dumpty',
    'A Drone',
    'Johannes Kepler',
    'Joe Camel',
    'Free Willy',
    'David Carradine',
    'Carlos Danger (anthony Weiner)',
    'John Hancock',
    'Joe Biden',
    'Kim Jong-il',
    'Mr. Rogers',
    'Fetus',
    'Alex Trebek With A Mustache',
    'Alex Trebek Without A Mustache',
    'A Virgin',
    'Crocodile Dundee',
    'The Kool-aid Man',
    'Andrea Yates',
    'Josephine Baker',
    'Lance Armstrong',
    'John Henry',
    'Miss Piggy',
    'Anthony Weiner',
    'A Lab Rat',
    'Tom Selleck\'s Mustache',
    'A Close Talker',
    'Yoko Ono',
    'Roger Ebert',
    'Kevin Bacon',
    'A Gerbil',
    'The Shark From Jaws',
    'The Boogeyman',
    'Your Evil Twin',
    'A T. Rex',
    'Rip Van Winkle',
    'The Winklevii',
    'Colonel Mustard',
    'A Swinger',
    'Cesar Millan',
    'A Nutcracker',
    'Rick James',
    'Gene Wilder',
    'A Werewolf',
    'Bob Ross',
    'Thomas Kinkade',
    'A Planeteer',
    'You',
    'Honey Boo Boo',
    'A Nihilist',
    'Phineas Gage',
    'Ricardo Montalbán',
    'A Redshirt',
    'David Attenborough',
    'A Catholic Priest',
    'The Id',
    'Yorick',
    'Jim Jones',
    'A Man From Nantucket',
    'Bobby Fischer',
    'Rob Ford',
    'Oskar Schindler',
    'Ouroboros',
    'Lot\'s Wife',
    'Catherine The Great',
    'Catherine The Great\'s Horse',
    'William Henry Harrison',
    'A Horse-sized Duck',
    'Jareth, The Goblin King',
    'A Dungeon Master',
    'Log Lady',
    'Tycho Brahe',
    'Cocaine Bear',
    'Baby Einstein',
    'Anita Hill',
    'A Dog Doing Yoga',
    'A Streaker',
    'Robert Hamilton',
    'Dramatic Chipmunk',
    'Sting',
    'Priapus',
    'Your High School Gym Teacher',
    'The Noble Savage',
    'Bartleby The Scrivener',
    'Grape Lady',
    'Pedobear',
    'Judas Iscariot',
    'Lolita',
    'Siri',
    'Silvio Berlusconi',
    'The Dread Pirate Roberts',
    'Harry Houdini',
    'The Sorcerer\'s Apprentice',
    'Honey Boo Boo',
    'Koko',
    'The 800 Pound Gorilla',
    'Charizard',
    'Portnoy',
    'The Boy Who Cried Wolf',
    'Roland The Farter, Flatulist To The King',
    'Nicholas Georgiton',
    'A Civil War Reenactor',
    'Mia Hamm',
    'Dr. Quinn, Medicine Woman',
    'Captain Ahab',
    'Oprah\'s Best Friend (gayle)',
    'Skeletor',
    'Star Wars Kid',
    'A Merman',
    'A Damsel In Distress',
    'Clippy',
    'The 1%',
    'Helen Keller',
    'A Mormon',
    'The Walrus',
    'Robocop',
    'Betsy Ross',
    'Big Brother',
    'Tubgirl',
    'The Superego',
    'Frogger',
    'Conjoined Twins',
    'Comic Book Guy',
    'Dr. Mario',
    'A Troll Doll',
    'A Dead Horse',
    'An Amish',
    'Dikembe Mutombo',
    'Lady Gaga\'s Meat Dress',
    'Kenny G',
    'Solange Knowles',
    'A Pug',
    'The Invisible Man',
    'Carrie',
    'Prancer',
    'Hal-9000',
    'An Immoveable Object',
    'Chairy',
    'The Elephant That Thomas Edison Electrocuted (topsy)',
    'The Soup Nazi',
    'Mother Teresa',
    'David Blaine',
    'Lennie Small',
    'Bill Clinton',
    'Flappy Bird',
    'The Übermensch',
    'The Dude',
    'A Rat King',
    'Icarus',
    'A Child Soldier',
    'An Unstoppable',
    'Force',
    'Kate Bush',
    'A Cyberbully',
    'A Never Nude',
    'A Juggalo',
    'A Doomsday Prepper',
    'The Robber From Settlers Of Catan',
    'Marie Antoinette',
    'Your Own Shadow',
    'Werner Herzog',
    'Dolph Lundgren',
    'The Jesus',
    'David Hasselhoff',
    'Right Said Fred',
    'A Flautist',
    'A Coke Mule',
    'The Ego',
    'A Manic Pixie Dream Girl',
    'Greg Louganis',
    'A Pufferfish',
    'Ms. Pac-man',
    'General Butt Naked',
    'Nyan Cat',
    'Pharell\'s Hat',
    'A Blue Man',
    'A Nigerian Prince',
    'Afro Ninja',
    'A Basic Bitch',
    'Myspace Tom',
    'A Cosplayer',
    'A Bottom',
    'Sinéad O\'connor',
    'David After Dentist',
    'Steve Irwin, The Crocodile Hunter',
    'Dick Armey',
    'Keyboard Cat',
    'A N00b',
    'Cindy Sherman',
    'Dolly The Sheep',
    'An Eager Beaver',
    'Punxsutawney Phil',
    'Little Mikey',
    'Michael J. Fox',
    'The Elephant Man',
    'Aaron Burr',
    'Jackson Galaxy',
    'Goose',
    'Nicolas Cage',
    'Benjamin Button',
    'The Lawnmower Man',
    'Commander William T. Riker',
    'The Zodiac Killer',
    'E. Honda',
    'Carlton Banks',
    'Miss Havisham',
    'Bees!',
    'Gizmo',
    'Quetzalcoatl',
    'Mother Brain',
    'Balki Bartokomous',
    'Slender Man',
    'A Freckleface',
    'The Astronaut Who Drove Across The Country Wearing Space Diapers To Kidnap Her Boyfriend',
    'Manti Te\'o\'s Girlfriend',
    'Stefon',
    'Colonel Angus',
    'Greedo',
    'Godot',
    'Chris Hadfield',
    'Admiral Ackbar',
    'Raskolnikov',
    'Hester Prynne',
    'Stephen Hawking',
    'Duck Hunt Dog',
    'The Last Unicorn',
    'Florida Man',
    'King Hippo',
    'Not A Dick',
    'Samson',
    'David Foster Wallace',
    'A Honey Badger',
    'A Highlander',
    'Dr. Zaius',
    'Sneezing Baby Panda',
    'Rasputin',
    'Marcel Marceau',
    'Howard Hughes',
    'Ham',
    'Royal Tenenbaum',
    'The Earl Of Sandwich',
    'Brian Boitano',
    'Archimedes',
    'Carl Sagan',
    'Lisa "left Eye" Lopes',
    'Lady Godiva',
    'Jacob The Jeweler',
    'Levar Burton',
    'The Prophet Muhammad (pbuh)',
    'Dick Cheney\'s Pacemaker',
    'Zelda Fitzgerald',
    'Charles Ponzi',
    'Frida Kahlo',
    'Harriet Tubman',
    'Uncle Ben',
    'Mrs. O\'leary\'s Cow',
    'Sisyphus',
    'John Wayne Gacy, Jr.',
    'Mama Cass',
    'Archduke Franz Ferdinand',
    'Clarence Thomas',
    'Eva Braun',
    'André The Giant',
    'The Lindbergh Baby',
    'A Mall Santa',
    'Vidal Sassoon',
    'The Stay Puft Marshmallow Man',
    'Gregor Samsa',
    'A Bassoonist',
    'Grizzly Man (timothy Treadwell)',
    'Joyce Carol Oates',
    'John Philip Sousa',
    'Typhoid Mary',
    'Grizzly Adams',
    'Patient Zero',
    'The Alien From Alien',
    'A Larper',
    'Johnnie Cochran',
    'Juan Valdez',
    'Marion Barry',
    'Sweeney Todd',
    'A Chimney Sweep',
    'Ghost Dog',
    'Marina Abramović',
    'She-hulk',
    'Terri Schiavo',
    'Mike Hunt',
    'The Guy Who Threw His Shoes At George W. Bush',
    'Terry Richardson',
    'R. Kelly',
    'Colton Burpo',
    'Joan Of Arc',
    'A Top',
    'Monica Lewinsky',
    'Area Man',
    'Jack Skellington',
    'A Power Bottom',
    'Schrödinger\'s Cat',
    'Mr. Wizard',
    'Double Rainbow Guy',
    'Kindergarten Cop',
    'Fabio',
    'David Caruso',
    'Jack Kevorkian',
    'Deepak Chopra',
    'Joey Chestnut',
    'Grumpy Cat',
    'Jiro',
    '8 Maids-a-milking',
    'John Wayne Bobbitt',
    'Feminist Ryan Gosling',
    'A Reptilian',
    'Wilford Brimley',
    'A Boss',
    'The Black Guy From The Shining (scatman Crothers)',
    'John Mcafee',
    'Chris Farley',
    'A Booth Babe',
    'Lil Bub',
    'Grimace',
    'Sad Keanu',
    'Xena, Warrior Princess',
    'Banksy',
    'Octopussy',
    'Ruth Bader Ginsburg',
    'Joaquin Phoenix\'s Forehead',
];
